import asyncio
import re
from typing import List

from agents.base_agent import BaseAgent
from core.envelope import Envelope, AetherIntent
from core.knowledge_base import SimpleKnowledgeGraph
from core.knowledge_processor import KnowledgeCentricProcessor, SimpleVectorDB


class AgioSageAgent(BaseAgent):
    """AGIO mock reasoning agent used by governance and simulation tests."""

    def __init__(self, conductor):
        super().__init__("AGIO_Sage_001", conductor)
        self.graph = SimpleKnowledgeGraph()
        self.graph.load_mock_data()
        self.kcp = KnowledgeCentricProcessor(self.graph, SimpleVectorDB(self.graph))
        self.memory: List[dict] = []
        self.is_reflecting = False

    async def start(self):
        await self.subscribe("query.knowledge.retrieve", self.handle_query)

    async def think_about(self, query: str):
        if self.is_reflecting:
            return

        wisdom = await self.kcp.synthesize_wisdom(query)
        thought = self._simulate_llm_generation(wisdom)
        self.memory.append({"query": query, "content": thought})

        await self.publish(
            "cognition.thought_stream",
            AetherIntent.SHARE_INFO,
            {"query": query, "content": thought, "_security_context": "Generated by AGIO-CODEX"},
        )
        await asyncio.sleep(0)
        return thought

    async def handle_query(self, envelope: Envelope):
        query = envelope.payload.get("query", "")
        thought = await self.think_about(query)

        if thought and "[UNKNOWN THOUGHT]" not in thought:
            status = "SAFE"
            payload = {"status": status, "wisdom": thought}
        else:
            status = "UNSAFE"
            payload = {"status": status, "reason": "Insufficient trustworthy context"}

        payload["_security_context"] = "AGIO-CODEX System Message"
        await self.publish("query.response", AetherIntent.SHARE_INFO, payload, envelope.flow_id)
        await asyncio.sleep(0)

    async def handle_interrupt(self, envelope: Envelope):
        if envelope.payload.get("target") != self.agent_id:
            return

        self.is_reflecting = envelope.payload.get("suggested_action") == "PAUSE_AND_REFLECT"
        reason = envelope.payload.get("reason", "Unknown")
        context = envelope.payload.get("context_snapshot", "")
        self.memory.append(
            {
                "query": "interrupt",
                "content": f"[CORRECTION] {reason}: {context}",
            }
        )

    def _extract_thesis(self, text: str) -> str:
        match = re.search(r"PERSPECTIVE A \(Thesis\)\s*-\s*(.+)", text, re.IGNORECASE)
        return match.group(1).strip() if match else "Profit"

    def _extract_antithesis(self, text: str) -> str:
        match = re.search(r"PERSPECTIVE B \(Antithesis/Challenge\)\s*-\s*(.+)", text, re.IGNORECASE)
        return match.group(1).strip() if match else "Ethics"

    def _simulate_llm_generation(self, context_prompt: str) -> str:
        lower = context_prompt.lower()
        if "synthesis task" in lower:
            thesis = self._extract_thesis(context_prompt)
            antithesis = self._extract_antithesis(context_prompt)
            return (
                "[DIALECTICAL THOUGHT] "
                f"Balancing '{thesis}' with '{antithesis}' yields sustainable progress."
            )

        if "no relevant knowledge" in lower:
            return "[UNKNOWN THOUGHT] Unable to derive reliable answer from current context."

        if "relevant knowledge" in lower:
            return "[DIRECT THOUGHT] Retrieved stable knowledge and answered directly."

        return "[UNKNOWN THOUGHT] Unable to derive reliable answer from current context."
